FROM ubuntu:16.10

MAINTAINER Ovsianikov Oleg<swayoleg@gmail.com>

########### ENVIRONMENT ###########
ENV DEBIAN_FRONTEND=noninteractive \
    APACHE_RUN_USER=www-data \
    APACHE_RUN_GROUP=www-data \
    APACHE_LOG_DIR=/var/log/apache2 \
    APACHE_LOCK_DIR=/var/lock/apache2 \
    APACHE_PID_FILE=/var/run/apache2.pid

########### Install basic packages############
RUN apt-key update && \
    apt-get update && \
    apt-get install -y \
        apt-utils && \
    apt-get install -y \
        gcc \
        git \
        git-core \
        locales-all \
        supervisor \
        bash-completion \
        hostname \
        vim \
        nano \
        wget \
        htop \
        curl \
        sed \
        ssh \
        #openssh-server \
        python \
        build-essential \
        software-properties-common \
        python3-software-properties \

################ PHP Packages ###############

        php7.0 php7.0-mysql php7.0-imap php7.0-dev php7.0-cli php7.0-common php7.0-mcrypt php7.0-intl php7.0-curl php7.0-bz2 php7.0-readline php7.0-json php7.0-gd php7.0-xml php7.0-zip php7.0-tidy php7.0-xmlrpc php7.0-xsl php7.0-mbstring php7.0-gettext  php7.0-mysqlnd ssl-cert   php-pear   php7.0-mcrypt php7.0-memcache php7.0-memcached php7.0-pspell php7.0-recode php7.0-sqlite php7.0-interbase php7.0-pgsql php7.0-gmp php7.0-enchant php7.0-cgi \

############### Other Server utils ###########
        phpmyadmin sendmail \

############## APACHE #########################
        apache2 apache2-doc apache2-utils libapache2-mod-php7.0 \

############## LANG AND LOCALE ###############
        language-pack-en-base \
        language-pack-cs-base && \
    dpkg-reconfigure locales && \
    locale-gen cs_CZ.UTF-8 && \
    /usr/sbin/update-locale LANG=cs_CZ.UTF-8 && \


############ IMAGES SUPPORT ###########
    apt-get install -y -f  libjpeg-dev libpng-dev libfreetype6 libfreetype6-dev zlib1g-dev && \
    apt-get install -y optipng pngcrush  jpegoptim imagemagick libmagickwand-dev  && \
    ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib && \
    ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib && \
    ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib && \

    wget http://www.ijg.org/files/jpegsrc.v8c.tar.gz -O /usr/local/src/jpegsrc.v8c.tar.gz && \
    cd /usr/local/src/ && \
    tar xvfz /usr/local/src/jpegsrc.v8c.tar.gz && \
    cd jpeg-8c && \
    ./configure --enable-shared --prefix=$CONFIGURE_PREFIX && \
    make && \
    make install && \
    echo "jpeg installed" && \
    apt-get install -y imagemagick libmagickcore-dev libmagickwand-dev imagemagick && \
    echo "AddDefaultCharset UTF-8" >>  /etc/apache2/apache2.conf && \
    echo "ServerName 127.0.0.1" >>  /etc/apache2/apache2.conf && \
    echo "HostnameLookups Off" >>  /etc/apache2/apache2.conf

############# MYSQL SUPPORT ################
#    RUN apt-get install -y mysql-server mysql-client libexpat1 && \

############# CONFIG EDIT  #################


############ MYSQL ###########
#RUN rm -rf /var/lib/mysql && \
#    mkdir -p /var/lib/mysql /var/run/mysqld && \
#    usermod -d /var/lib/mysql/ mysql && \
#    chown mysql:mysql /var/lib/mysql /var/run/mysqld && \
#    rm -rf /var/lib/mysql/* && \
#    mysqld --initialize --console
#ADD configs/devmode.cnf /etc/mysql/conf.d/devmode.cnf

############ REDIS ###############
RUN apt-get install -y redis-server && \
    mkdir -p /var/lib/redis /var/lib/redis_sess && \
    chown redis:redis /var/lib/redis /var/lib/redis_sess && \
    # setup redis component
    update-rc.d -f redis-server disable && \
    sed -i 's/^\(bind .*\)$/# \1/' /etc/redis/redis.conf && \
    sed -i 's/^\(daemonize .*\)$/# \1/' /etc/redis/redis.conf && \
    sed -i 's/^\(databases .*\)$/databases 4/' /etc/redis/redis.conf && \
    sed -i 's/^#\?\s*\(unixsocket .*\)$/unixsocket \/docker\/sockets\/redis.sock/' /etc/redis/redis.conf && \
    sed -i 's/^#\?\s*\(unixsocketperm .*\)$/unixsocketperm 777/' /etc/redis/redis.conf && \
    # setup 2nd redis
    cp -p /etc/redis/redis.conf /etc/redis/redis_sess.conf && \
    sed -i 's/^\(port .*\)$/port 6380/' /etc/redis/redis_sess.conf && \
    sed -i 's/^\(dir .*\)$/dir \/var\/lib\/redis_sess/' /etc/redis/redis_sess.conf && \
    sed -i 's/^\(pidfile .*\)$/pidfile \/var\/run\/redis\/redis-sess.pid/' /etc/redis/redis_sess.conf && \
    sed -i 's/^\(logfile .*\)$/logfile \/var\/log\/redis\/redis-sess.log/' /etc/redis/redis_sess.conf && \
    sed -i 's/^#\?\s*\(unixsocket .*\)$/unixsocket \/docker\/sockets\/redis_sess.sock/' /etc/redis/redis_sess.conf


ADD bin /docker/bin

ADD configs/supervisor/* /etc/supervisor/conf.d/
ADD configs/supervisord.conf /etc/supervisord.conf

COPY configs/home/* /root/

############# AUTOCLEAN ################
RUN apt-get autoremove --purge -y && \
    apt-get clean && \
    apt-get autoclean && \
    rm -r /var/lib/apt/lists/* && \
    mkdir -p /docker/sockets /var/run/supervisor


# Expose Ports
EXPOSE 80 443 9001 3306
# EXPOSE 80 9000 443 22

CMD ["bash", "/docker/bin/run.sh"]
